import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'
const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Home() {
  const { data, error } = useSWR('https://lewisapi.glitch.me/api/status/989183816973295636', fetcher)

  const durum = data?.pop?.profil?.durum
  const statusColor = data?.pop?.profil?.durum
  const stColor = statusColor == "online" ? "bg-green-400" : statusColor == "idle" ? "bg-yellow-400" : statusColor == "dnd" ? "bg-red-400" : "bg-gray-500"
  const aktivite = data ? data.pop.aktiviteler.find((x) => x.type === 0) : null;
                 
  
  return (
    <>
      <Head>
        <title>Lewis API - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="mt-8 m-4 flex justify-center">
    
    <div className="card card-compact w-max bg-base-100 shadow-xl">
   
         <div className="mt-4 place-self-center flex justify-center">
<figure><img  src={`https://cdn.discordapp.com/avatars/${data?.pop?.profil?.id }/${ data?.pop?.profil?.avatar }.png`} alt="Movie"/></figure>
      </div>
      
      
        <div className="card-body">
  <h2 className="card-title">{ data?.pop?.profil?.kullanici_adi } </h2>
  <p className="text-lg font-semibold mb-4">Merhaaba ben bir Lewis API Örneğiyim.</p>
    
           <div className="font-mono text-sm flex break-words">
   <div className={ stColor + " border-gray-300  w-6 h-6 border-2 dark:border-gray-800 rounded-full"}>  </div>
   <a className="flex-auto ml-2">Discord'da { data?.pop?.profil?.durum_tr } </a>

 </div>
    
           <div>
           { data?.pop.spotify_durumu == true &&
   <div className="flex items-center font-mono text-sm break-words flex  text-center ">
     <img className='w-7 h-7 rounded-full' src={ data?.pop?.spotify?.album_resmi } /> <p class="ml-2 flex ml-2 font-medium"> Spotify'da { data?.pop?.spotify?.sanatci + " - " +  data?.pop?.spotify?.sarki_adi } Dinliyorum!</p>
 </div>
}
  
   </div> 

       <div>  
   { aktivite ? (


<div className="font-mono flex flex-row text-sm ">
<img className="w-7 h-7 rounded-lg" src={`https://cdn.discordapp.com/app-assets/${aktivite.applicationId}/${aktivite.assets.largeImage}.png`}></img>  <a className="ml-2 font-medium">{aktivite.name} {aktivite.details} </a>
</div>
) : null
}
</div>
     
  <div className="card-actions justify-end">
      
           
      </div>
    </div>
  </div>          
    </div>

    </>
  )
}


